### ISSUE TITLE
more details in readme / disclaimer for managed workflow

### ISSUE THREAD

**Issue by castdrian** [outsung/expo-dynamic-app-icon#2]
for android this requires the manifest to be edited and expo doesn't let you do that very easily, you have to make a patch that runs on compiletime, ideally the readme should mention that this is required for the managed workflow or perhaps maybe even provide an example patch

**Comment by outsung** [comment]
this library assumes to use eas build.
as shown in readme, add a plugin to app.json
and run "expop prebuild" to automatically set up Android Manifest.

**Comment by outsung** [comment]
and if you develop with expo-dev-client
rebuild and run with `expo start --dev-client` works fine

**Comment by castdrian** [comment]
yeah it does work but uses the legacy icon instead of the dynamic icon which makes it look really bad
![qemu-system-x86_64_X6t3datx5H](https://user-images.githubusercontent.com/22133246/216401044-aecde66b-44b4-4b61-a735-92304f7f4146.png)

**Comment by outsung** [comment]
hum... ok let me check with new issue #3
