### ISSUE TITLE
no functionality when built via xcodebuild

### ISSUE THREAD

**Issue by castdrian** [outsung/expo-dynamic-app-icon#20]
(note using https://github.com/outsung/expo-dynamic-app-icon/pull/18 for sdk 50 compatability)

it seems that the package has no effect when the application is built as standalone using xcodebuild instead of expo cli

using `expo run:ios` works perfectly fine both on iOS simulator and real iOS device
using 
```
 expo prebuild --platform=ios && cd ios && xcodebuild -workspace project.xcworkspace -scheme project -configuration Release -derivedDataPath build -destination generic/platform=iOS CODE_SIGN_IDENTITY=\"\"
```
to build a standalone iOS app however yields in no icon change whatsoever

I'm not sure what exactly the differences are but I think xcodebuild might be using a different bundling configuration, the Build Phase that bundles the rn files launches `expo export:embed` according to the script so perhaps that somehow omits assets, I am truly not sure, I tried everything to figure out what exactly causes this but alas was not successful

**Comment by coderpr0grammer** [comment]
That's weird, for me even using `npx expo run:ios` it doesn't actually change the icon, just returns "DEFAULT" every time. Can you share your code please?

**Comment by castdrian** [comment]
nothing special just the config plugin and calling the function, your issue sounds like you might need a clean rebuild of all native code

**Comment by coderpr0grammer** [comment]
Not sure since I deleted the ios file and ran `npx expo run ios` again, I have a feeling it might be a similar issue to yours in relation to the files maybe

**Comment by castdrian** [comment]
nope, my issue applies to all dynamic app icon libs, not just this one, they all fail when the bundling happens outside of the expo client, you should prolly clean the build cache and whatnot

**Comment by castdrian** [comment]
This seems to be related to the difference between paid and local certificates assigning app ids in a different manner, I don’t believe there is a way to circumvent this behavior
