### ISSUE TITLE
Feature request : implements getIconName()

### ISSUE THREAD

**Issue by frshog** [outsung/expo-dynamic-app-icon#5]
Hi, thank you very much for you job on expo-dynamic-app-icon.

On Android, after call of setAppIcon(), on first loss of app focus, the App is closed (certainly to apply icon).
So, if App request for permissions (notification, localisation or else), it closes automatically : it looks like a bug for the user.

Is there anyway to avoid that on android ?

Morever, could you easly  implements getIconName() in addition to setAppIcon() : it will allow to check if icon need to be changed.
On some Android devices, install/uninstall restores initial Icon but storage is restored as before, so it's not possible to use storage to know if icon App has been changed by reinstallation.

Thanks for your help.

**Comment by outsung** [comment]
@frshog 
Thanks for the coffee.

I added the `getAppIcon` (#6)
Check it out. (v1.1.8)

And I didn't expect it to turn off when I asked for permission on Android.
I'll take a look at this and fix it. It might take some time.

**Comment by frshog** [comment]
@outsung 
Thanks a lot for added getAppIcon, it works fine ;-)
